version: "3.3"

services:
  alkis:
    image: docker.archikart.de/archikart/alkis_gid7_v79:latest
    ports:
      - ${ALKIS_GID7_PORT}:22
    networks:
      - alkis-net
    volumes:
      - alkis-filestore:/root/archikart/alkis/filestore
    depends_on:
      - postgis
    restart: unless-stopped
    links:
      - "postgis:archikart-postgis"
  postgis:
    image: docker.archikart.de/archikart/alkis_postgis_v79:latest
    ports:
      - ${ALKIS_POSTGIS_PORT}:5432
    networks:
      - alkis-net
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: archikart
    restart: unless-stopped
    shm_size: '6gb'
volumes:
  alkis-filestore: {}
  pg-data: {}
networks:
  alkis-net: {}
